modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kaleidoscope_tavern"
mandatory=true
versionRange="${kaleidoscope_tavern_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[15.0.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jade"
mandatory=false
versionRange="[11.13.1,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="curios"
mandatory=false
versionRange="[5.0.0,)"
ordering="AFTER"
side="BOTH"
